name: Test Custom GitHub Pages Action

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Run custom GitHub Pages documentation action

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repo X
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run custom documentation action
        uses: ./
        with:
          docs-dir: docs

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: theme/_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
